name: Github Pages
on:
  push:
    branches:
      - master
  schedule:
    # Run this script every 2 hrs
    #  */m hr day month day_of_week
    - cron:  '0 */2 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description Tag'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install and Run Node Script
        run: |
          npm install
          node ./src/build.js
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.